[web]
web1.ilya-serv.internal ansible_user=ilya-serv ansible_ssh_common_args="-o ProxyJump=ilya-serv@84.201.175.171 -o StrictHostKeyChecking=no"
web2.ilya-serv.internal ansible_user=ilya-serv ansible_ssh_common_args="-o ProxyJump=ilya-serv@84.201.175.171 -o StrictHostKeyChecking=no"
[zabbix]
zabbix.ilya-serv.internal ansible_user=ilya-serv ansible_ssh_common_args="-o ProxyJump=ilya-serv@84.201.175.171 -o StrictHostKeyChecking=no"
[elastic]
elasticsearch.ilya-serv.internal ansible_user=ilya-serv ansible_ssh_common_args="-o ProxyJump=ilya-serv@84.201.175.171 -o StrictHostKeyChecking=no"
[kibana]
kibana.ilya-serv.internal ansible_user=ilya-serv ansible_ssh_common_args="-o ProxyJump=ilya-serv@84.201.175.171 -o StrictHostKeyChecking=no"
